services:
  chronocat-docker:
    image: zglinus/chronocat-docker
    tty: true
    container_name: chronocat-docker
    restart: always
    ports:
      - "5900:5900"
      - "16530:16530"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - $PWD/qq/config:/home/user/.config/QQ
      - $PWD/qq/opt/QQ:/opt/QQ
      - $PWD/qq/usr/share/applications/qq.desktop:/usr/applications/qq.desktop
      - $PWD/qq/usr/share/doc/linuxqq/:/usr/share/doc/linuxqq/
      - $PWD/qq/usr/share/icons/hicolor/512x512/apps/qq.png:/usr/share/icons/hicolor/512x512/apps/qq.png
      - $PWD/data:/home/user
      - $PWD/qq/qq:/usr/bin/qq
