services:
  chronocat-docker:
    image: zglinus/chronocat-docker
    tty: true
    container_name: chronocat-docker
    restart: always
    ports:
      - "5900:5900"
      - "16530:16530"
      - "6081:6081"
    environment:
      - TZ=Asia/Shanghai
      - VNC_PASSWD=vncpasswd
    volumes:
      - $PWD/qq/config:/home/user/.config/QQ
