services:
  chronocat-docker:
    image: zglinus/chronocat-docker:3.1.2-13107
    tty: true
    container_name: chronocat-docker
    user: '1000:1000' # 以普通用户权限运行（可选）
    restart: always
    ports:
      - "5900:5900"
      - "16530:16530"
      - "6081:6081"
    environment:
      - TZ=Asia/Shanghai
      - VNC_PASSWD=vncpasswd
    volumes:
      - $PWD/qq/config:/home/user/.config/QQ
    healthcheck: # 健康检查（可选）
      test: ["CMD", "netstat", "-lnp", "|", "grep", "':43[0-9][0-9] '"]
      interval: 1m
      timeout: 10s
      retries: 3
